### ISSUE TITLE
TypeError: Cannot call method 'insert' of undefined

### ISSUE THREAD

**Issue by WadeWarren** [gwendall/meteor-mongo-algolia-sync#1]
``` javascript
TypeError: Cannot call method 'insert' of undefined
    at [object Object].Meteor.addCollectionPrototype.options [as syncAlgolia] (packages/gwendall_mongo-algolia-sync/lib.js:6:1)
```

I'm getting the above error when trying to sync a Mongo collection. The collection is already defined, but I cannot call syncAlgolia on it. :-/

**Comment by patrickml** [comment]
+1

**Comment by patrickml** [comment]
@WadeWarren It looks like this issue has to do with when you load `matb33:collection-hooks` in your application. If you are using `collection2` as well you have to add `matb33:collection-hooks` before that. https://github.com/matb33/meteor-collection-hooks/issues/62

**Comment by WadeWarren** [comment]
@patrickml Ah interesting - what's the best way to change the load order? Thanks!

**Comment by patrickml** [comment]
@WadeWarren you can go to the `.meteor` folder and change the `packages` file in there you will see the packages in the order added/needed also if you are adding collection2 package via another internal package add `matb33:collection-hooks` before collection2

**Comment by WadeWarren** [comment]
@patrickml Ah - easier than I expected. Thanks!
